default_platform(:android)

platform :android do
  desc "Prepare and build release App Bundle"
  lane :prepare do
    Dir.chdir "../.." do
      sh("flutter", "packages", "get")
      sh("flutter", "clean")
      sh("flutter", "build", "appbundle", "--release")
    end
  end

  desc "Push a new beta build to Google Play"
  lane :beta do
    prepare
    upload_to_play_store(
      track: 'beta',
      aab: "../build/app/outputs/bundle/release/app.aab"
    )
  end

  desc "Push a new release build to Google Play"
  lane :release do
    prepare
    upload_to_play_store(
      track: 'production',
      aab: "../build/app/outputs/bundle/release/app.aab"
    )
  end
end
